name: CI + Build Artifact Workflow

on:
  push:
    branches:
      - feature-1

  schedule:
    - cron: "25 10 * * *"

  workflow_dispatch:
  schedule:
    - cron: "25 10 * * *"

  workflow_dispatch:

env:
  IMAGE_NAME: tiny-health-app
  IMAGE_TAR: tiny-health-app.tar
  ARTIFACT_NAME: tiny-health-app-image

jobs:

  # =========================
  # Job 1 — CI (Run Tests)
  # =========================
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Show Python version
        run: python --version

      - name: Run tests
        run: python -m unittest discover -s tests -v

      - name: List repo files
        run: ls -R

      - name: Show Runner time
        run: date


  # =======================
  # Job 2 — Build Artifact
  # =======================
  build-artifact:
    runs-on: ubuntu-latest

    # ✅ dependency هنا
    needs: ci

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run tests again (safety check)
        run: python -m unittest discover -s tests -v

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export image
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ${{ env.IMAGE_NAME }}:run-${{ github.run_number }}
          outputs: type=docker,dest=${{ env.IMAGE_TAR }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.IMAGE_TAR }}
          retention-days: 7